#!/bin/bash
################################################################################
#
# Copyright (c) 2016, EURECOM (www.eurecom.fr)
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice, this
#    list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright notice,
#    this list of conditions and the following disclaimer in the documentation
#    and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
# ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
# ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
# The views and conclusions contained in the software and documentation are those
# of the authors and should not be interpreted as representing official policies,
# either expressed or implied, of the FreeBSD Project.
#
################################################################################
# file config-change
# brief manage the config changes of oai-enb service, and occurs everytime a new configuration value is updated (juju set)
# author navid.nikaein@eurecom.fr and A. B. Molini

set -ux
source $CHARM_DIR/utils/common
set_env_paths

if [ "$(config-get branch)" != "$(cat $CHARM_DIR/.branch)" ]; then
    $CHARM_DIR/hooks/upgrade-charm
fi

if [ "$(config-get revision)" != "$(cat $CHARM_DIR/.revision)" ]; then
    $CHARM_DIR/hooks/upgrade-charm
fi

###########################################################
juju-log "Setting up configuration in the $epc_conf_path file"
# file_name:spgw.conf
###########################################################

cp $openair_path/ETC/spgw.conf /usr/local/etc/oai/

# setup the iface, ip_address, ipv4_list for oaisim, sdn
iface=`config-get eth`
ipv4_list_start=`config-get ipv4_list_start`
ipv4_list_end=`config-get ipv4_list_end`
ipv6_list=`config-get ipv6_list`
PGW_MASQUERADE_SGI=`config-get PGW_MASQUERADE_SGI`
DEFAULT_DNS_IPV4_ADDRESS=`config-get DEFAULT_DNS_IPV4_ADDRESS`
DEFAULT_DNS_SEC_IPV4_ADDRESS=`config-get DEFAULT_DNS_SEC_IPV4_ADDRESS`

ipv4=`ifconfig $iface | egrep -o "inet addr:[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+" | egrep -o "[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+"`

# interface
sed -r -i "s/SGW_INTERFACE_NAME_FOR_S11/ s/\".*\"/\"$iface\"/" $epc_conf_path/spgw.conf
sed -r -i "s/SGW_INTERFACE_NAME_FOR_S1U_S12_S4_UP/ s/\"...\"/\"$iface\"/" $epc_conf_path/spgw.conf
sed -r -i "s/PGW_INTERFACE_NAME_FOR_SGI/ s/\".*\"/\"$iface\"/" $epc_conf_path/spgw.conf
# ip_address
sed -r -i "/SGW_IPV4_ADDRESS_FOR_S11/ s/\".*\"/\"$ipv4/12\"/" $epc_conf_path/spgw.conf
sed -r -i "/SGW_IPV4_ADDRESS_FOR_S1U_S12_S4_UP/ s/\".*\"/\"$ipv4/24\"/" $epc_conf_path/spgw.conf
sed -r -i "/PGW_MASQUERADE_SGI/ s/\"..\"/\"$PGW_MASQUERADE_SGI\"/" $epc_conf_path/spgw.conf
# ipv4_list
sed -r -i "/IPV4_LIST/,/\);/ s-\"[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+/[0-9]+\",-\"$ipv4_list_start\",-" $epc_conf_path/spgw.conf
# dns
sed -r -i "s/DEFAULT_DNS_IPV4_ADDRESS/ s/\".*\"/\"$DEFAULT_DNS_IPV4_ADDRESS\"/" $epc_conf_path/spgw.conf
sed -r -i "s/DEFAULT_DNS_SEC_IPV4_ADDRESS/ s/\".*\"/\"$DEFAULT_DNS_SEC_IPV4_ADDRESS\"/" $epc_conf_path/spgw.conf

sed -r -i "/OUTPUT/ s/\".*\"/\"CONSOLE\"/" $epc_conf_path/spgw.conf

juju-log "Setting up configuration in the $epc_conf_path file with default ones"

##############################################################################################

MME_UNIT_RUNNING=O

if [ -n "$(relation-ids mme)" ]; then
  for mme_id in $(relation-ids mme); do
    juju-log "the relation-ids of mme is "$mme_id""
    for unit in $(relation-list -r $mme_id); do
      mme_running=`relation-get -r $mme_id mme_running $unit`
      if [ "$mme_running" == "yes" ]; then
        MME_UNIT_RUNNING=$((MME_UNIT_RUNNING +1))
        # at least one mme is running among the ones connected to mme
        # so let's run spgw....beacuse we have changed some configuration
      fi
    done
  done

  if [ MME_UNIT_RUNNING -gt 0 ]; then
    juju-log "Running OAI-SPGW"
    $CHARM_DIR/hooks/start
    status-set active "OAI-SPGW is running"
  else
    juju-log "Service reconfigured but cannot to run"
    status-set blocked "Add relation to mme"
  fi
else
  juju-log "Need a mme relation to run"
  status-set maintenance "Waiting for active connection with mme to gather the last info to run OAI SPGW"
fi
