#!/bin/bash
################################################################################
#
# Copyright (c) 2016, EURECOM (www.eurecom.fr)
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice, this
#    list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright notice,
#    this list of conditions and the following disclaimer in the documentation
#    and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
# ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
# ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
# The views and conclusions contained in the software and documentation are those
# of the authors and should not be interpreted as representing official policies,
# either expressed or implied, of the FreeBSD Project.
#
################################################################################
# file upgrade-charm
# brief called when each time a charm is upgraded after the new charm
# contents have been unpacked
# author  navid.nikaein@eurecom.fr and A. B. Molini

# Best practice suggests you execute the hooks/install and
# hooks/config-changed to ensure all updates are processed

set -eux
source $CHARM_DIR/utils/common
set_env_paths

#service mme_gw stop || true # Stop the service
service epc_mme stop || true # Stop the service
service epc_spgw stop || true # Stop the service
$CHARM_DIR/hooks/install

#now we need to fill again the epc.conf with the data took from the relations as the epc.conf
#is a new one.

if [ -n "$(relation-ids hss)" ]; then
   #Fill again the epc.conf file since it has been downloaded a fresh installation...don't want to lose hss relation data in the configuration
   hss_id=`relation-ids hss`
   hss_unit=`relation-list -r $hss_id`
   hss_fqdn=`relation-get -r "$hss_id" hss_hostname $hss_unit`
   ip_address_hss=`relation-get ip_address`

   hss_hostname=${hss_fqdn%%.*}
   realm=`config-get realm`

   sed -r -i "s/(HSS_HOSTNAME[^\"]*)\".*\"/\1\"$hss_hostname\"/" $epc_conf_path/mme.conf
   # modify by subond
   #sed -r -i "s/(ConnectPerr[^\"]*)\".*\"/\1\"$hss_fqdn\"/" $epc_conf_path/freeDiameter/mme_fd.conf
   #sed -r -i "s/(ConnectTo[^\"]*)\".*\"/\1\"$ip_address_hss\"/" $epc_conf_path/freeDiameter/mme_fd.conf
   sed -r -i "/Identity/ s/\".*\"/\"`hostname`.$realm\"/" $epc_conf_path/freeDiameter/mme_fd.conf
   sed -r -i "/ConnectPeer/ s/\"hss.openair4G.eur\"/\"$hss_fqdn\"/" $epc_conf_path/freeDiameter/mme_fd.conf
   sed -r -i "/ConnectTo/ s-\"127.0.0.1\"-\"$ip_address_hss\"-" $epc_conf_path/freeDiameter/mme_fd.conf
   sed -r -i "s/No_SCTP/No_TCP/g" $epc_conf_path/freeDiameter/mme_fd.conf
   #sed -r -i "s/Prefer_TCP/#Prefer_TCP/" $epc_conf_path/freeDiameter/mme_fd.conf
   #sed -r -i "s/Prefer_TCP;/ /" ./mme_fd.conf
   #sed -r -i "s/Prefer_TCP/ /" ./mme_fd.conf
   sed -r -i "s/Prefer_TCP;/ /" $epc_conf_path/freeDiameter/mme_fd.conf
   sed -r -i "s/Prefer_TCP/ /" $epc_conf_path/freeDiameter/mme_fd.conf
   # end
fi

if [ -n "$(relation-ids epc)" ]; then
   #since tha data from both the hss and epc relations affect the epc.conf
   #I also need to grab the epc relation data(data sent by OAISIM or OAIeNB unit)
   #and fill the epc.conf with it, as this conf file is a new one.

   for tac in $(cat $CHARM_DIR/.tac_list | egrep "^[0-9]+ [0-9]+$"| cut --delimiter=" " -f 1); do

       if [ -z "$(egrep "MCC[ ]*=[ ]*\"$(config-get gummei_tai_mcc)\"[ ]*;[ ]*MNC[ ]*=[ ]*\"$(config-get gummei_tai_mnc)\"[ ]*;[ ]*TAC[ ]*=[ ]*\"$tac\"" $epc_conf_path/epc.conf)" ]; then
           sed -r -i "/TAI_LIST/a {MCC=\"$(config-get gummei_tai_mcc)\" ; MNC=\"$(config-get gummei_tai_mnc)\";  TAC = \"$tac\";}," $epc_conf_path/epc.conf
       fi

   done

fi
