#!/bin/bash
################################################################################
#
# Copyright (c) 2016, EURECOM (www.eurecom.fr)
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice, this
#    list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright notice,
#    this list of conditions and the following disclaimer in the documentation
#    and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
# ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
# ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
# The views and conclusions contained in the software and documentation are those
# of the authors and should not be interpreted as representing official policies,
# either expressed or implied, of the FreeBSD Project.
#
################################################################################
# file hss-relation-departed
# brief called when the hss-epc relation is removed
# author  navid.nikaein@eurecom.fr and A. B. Molini

set -eux
source $CHARM_DIR/utils/common
set_env_paths

rm -f $CHARM_DIR/.trigger

juju-log "Stopping OAI EPC"

#if hss stops running, EPC shouldn't be running because functionalities and procedures
#rely on the HSS.(auth,....)
#service mme_gw stop || true
service mme stop || true

juju-log "Deleting the EPC stdout and stderr files"
rm -f /srv/.out /srv/.err

juju-log "Delete any relation data trace"

hss_fqdn=`relation-get hss_hostname`
ip_address_hss=`relation-get ip_address`
realm=`config-get realm`
sed -r -i "/$hss_fqdn/ d" /etc/hosts
sed -r -i "s/(HSS_HOSTNAME[^\"]*)\".*\"/\1\"\"/" $epc_conf_path/mme.conf
# modify by subond
# sed -r -i "s/(ConnectPerr[^\"]*)\".*\"/\1\"$hss_fqdn\"/" $epc_conf_path/freeDiameter/mme_fd.conf
# sed -r -i "s/(ConnectTo[^\"]*)\".*\"/\1\"$ip_address_hss\"/" $epc_conf_path/freeDiameter/mme_fd.conf
sed -r -i "/Identity/ s/\".*\"/\"`hostname`.$realm\"/" $epc_conf_path/freeDiameter/mme_fd.conf
sed -r -i "/ConnectPeer/ s/\"hss.openair4G.eur\"/\"$hss_fqdn\"/" $epc_conf_path/freeDiameter/mme_fd.conf
sed -r -i "/ConnectTo/ s-\"127.0.0.1\"-\"$ip_address_hss\"-" $epc_conf_path/freeDiameter/mme_fd.conf
sed -r -i "s/No_SCTP/No_TCP/g" $epc_conf_path/freeDiameter/mme_fd.conf
#sed -r -i "s/Prefer_TCP/#Prefer_TCP/" $epc_conf_path/freeDiameter/mme_fd.conf
#sed -r -i "s/Prefer_TCP;/ /" ./mme_fd.conf
#sed -r -i "s/Prefer_TCP/ /" ./mme_fd.conf
sed -r -i "s/Prefer_TCP;/ /" $epc_conf_path/freeDiameter/mme_fd.conf
sed -r -i "s/Prefer_TCP/ /" $epc_conf_path/freeDiameter/mme_fd.conf
# end

status-set blocked "waiting for HSS connection for being run"

#stop every enodeB attached to this epc service unit
if [ -n "$(relation-ids mme)" ]; then
    for mme_id in $(relation-ids mme); do
        juju-log ""$mme_id""
        relation-set -r "$mme_id" mme_running=no
    done
fi
