#!/bin/bash
################################################################################
#
# Copyright (c) 2016, EURECOM (www.eurecom.fr)
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice, this
#    list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright notice,
#    this list of conditions and the following disclaimer in the documentation
#    and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
# ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
# ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
# The views and conclusions contained in the software and documentation are those
# of the authors and should not be interpreted as representing official policies,
# either expressed or implied, of the FreeBSD Project.
#
################################################################################
# file epc-relation-changed
# brief called when the enb-epc relation is changed
# author  navid.nikaein@eurecom.fr and A. B. Molini
# modity by subond, at Nov 4 2016
set -ex
source $CHARM_DIR/utils/common
set_env_paths

juju-log "Retrieving SPGW relation info"
ip_address_sgpw=`relation-get spgw_ip`
spgw_running=`relation-get spgw_running`
trigger_restart=`relation-get trigger_restart`

juju-log "trigger_restart=$trigger_restart, spgw_running=$spgw_running, relation_ids_mme=$(relations-ids mme)"

if [ ! -f $CHARM_DIR/.trigger ]; then
  echo "0" > $CHARM_DIR/.trigger
fi

if [ -z "$ip_address_sgpw" ]; then
  juju-log "Data of spgw not sent yet"
  exit 0
fi

#if [ "$spgw_running" == "no" ]; then
#  ckeck_mme_process
#  if [ $status -eq 0 ]; then
#    juju-log "The spgw relation is broken..."
#    status-set blocked "Add the spgw relation"
#  else
#    juju-log "Wait for db relation before starting MME"
#    status-set blocked "Add the db relation"
#  fi
#  exit 0
#fi

# add data of spgw to mme.config
sed -r -i "/SGW_IPV4_ADDRESS_FOR_S11/ s-\".*\"-\"$ip_address_sgpw/24\"-" $epc_conf_path/mme.conf

if [ "$spgw_running" == "no" ]; then
#  service mme restart || true
   $CHARM_DIR/actions/restart
  juju-log "Add spgw info to configure file...and restart oai mme"
  check_mme_process
  if [ $status -eq 0 ]; then
    juju-log "Add spgw relation...and mme is restarting"
    status-set active "OAI MME is re-running..."
    relation-set mme_running=yes
    check_mme_connection
    status-set active "OAI MME is connected to HSS"
  else
    juju-log "Wait for db relation before starting MME"
    status-set blocked "Add the db relation and run mme"
  fi
fi
